### ISSUE TITLE
supports the latest ElasticSearch?

### ISSUE THREAD

**Issue by ghost** [liangshiw/SharpPlugs#2]
ElasticSearch removed type in version 7.x, currently sharpplug. ElasticSearch component, supports the latest ElasticSearch?

**Comment by realLiangshiwei** [comment]
I will support version 7.0.

**Comment by ghost** [comment]
> I will support version 7.0.

Great, I'll wait for this support for Elastic Search 7.X!

**Comment by BootsShu** [comment]
Does this client already support 7.x?

**Comment by BootsShu** [comment]
> > 我会支持7.0版。
> 
> 好的，我会等待对弹性搜索7.X的这种支持！

Does this client already support 7.x?

**Comment by ghost** [comment]
Does this client already support 7.x?

**Comment by realLiangshiwei** [comment]
Focus branch https://github.com/liangshiw/SharpPlugs/tree/feature/ElasticSearch7.X
I will improve it the next week.

**Comment by realLiangshiwei** [comment]
I am considering redesigning the entire framework, but before that, I will upgrade the adaptation of es first.

**Comment by BootsShu** [comment]
> 我正在考虑重新设计整个框架，但在此之前，我将首先升级es的改编。

That would be great.

**Comment by realLiangshiwei** [comment]
done 
https://www.nuget.org/packages/SharpPlug.ElasticSearch/1.2.3
