### ISSUE TITLE
SharpPlug.ElasticSearch，使用SniffingConnectionPool异常问题

### ISSUE THREAD

**Issue by ghost** [liangshiw/SharpPlugs#3]
1、使用：SniffingConnectionPool，产生如下堆栈异常：
Invalid NEST response built from a unsuccessful () low level call on HEAD: /_alias/blog
# Audit trail of this API call:
 - [1] SniffOnStartup: Took: 00:00:00.3568294
 - [2] SniffSuccess: Node: http://localhost:9200/ Took: 00:00:00.3385112
 - [3] PingFailure: Node: http://172.18.0.2:9200/ Exception: PipelineException Took: 00:00:01.2995444
 - [4] SniffOnFail: Took: 00:00:01.3101759
 - [5] SniffFailure: Node: http://172.18.0.2:9200/ Exception: PipelineException Took: 00:00:01.2545065
# OriginalException: Elasticsearch.Net.ElasticsearchClientException: Failed sniffing cluster state.. Call: unknown resource ---> Elasticsearch.Net.PipelineException: Failed sniffing cluster state. ---> Elasticsearch.Net.PipelineException: An error occurred trying to write the request data to the specified node. ---> System.Net.Http.HttpRequestException: 由于目标计算机积极拒绝，无法连接。 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。

2、使用StaticConnectionPool，一切正常，您为什么要使用SniffingConnectionPool呢，是考虑到什么原因吗？；

国庆愉快。

**Comment by realLiangshiwei** [comment]
这个问题我记得解决了，你稍等，我检查一下

**Comment by ghost** [comment]
您好，这个问题，可以解决吗？

**Comment by realLiangshiwei** [comment]
这属于es的配置问题,你可以参考 
https://github.com/elastic/elasticsearch-net/issues/3351#issuecomment-411982868
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html

**Comment by ghost** [comment]
我在研究研究，这配置看起来有些晕乎晕乎的。

**Comment by ghost** [comment]
谢谢。
